# Generated by Django 5.1.2 on 2024-11-19 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bankloan',
            fields=[
                ('loan_id', models.IntegerField(primary_key=True, serialize=False)),
                ('loan_type', models.CharField(max_length=30)),
                ('loan_amt', models.IntegerField()),
                ('cust_name', models.CharField(max_length=30)),
                ('cust_acno', models.IntegerField()),
            ],
        ),
    ]
